name: Deploy workflow
on: [push, workflow_dispatch]
jobs:
  Testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v6
      - name: Setup the Node js
        uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Install the dependencies
        run: npm ci
      - name: Test the code
        run: npm test
  buildJob:
    needs: Testjob
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v6
    - name: Setup the Node js
      uses: actions/setup-node@v6
      with:
        node-version: 18
    - name: Install the dependencies
      run: npm ci
    - name: Build the code 
      run: npm run build 
    - name: upload the artifact
      uses: actions/upload-artifact@v6
      with:
        name: build_files
        path: build/
  DeployJob:
    needs: buildJob
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v6
      - name: Install the node js
        uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Install the dependencies
        run: | 
            npm ci
            echo "Deploying ....."
